### ISSUE TITLE
Field Type is not being enforced

### ISSUE THREAD

**Issue by pradeep-kumar-ioent** [ejpcmac/typed_struct#41] opened 2022-10-11 11:27 UTC
It doesn't make a lot of sense for me to just define the types and not enforce.

Example -
I create a typed struct like this -

```
defmodule WhatEver do
 use TypedStruct

  typedstruct do
    field :SomeField, List.t()
  end
end
```

and then it is still allowing this to be set other than list - 
```
struct(WhatEver, %{SomeField: 123})

> %WhatEver{SomeField: 123}
```

Would make more sense if it could actually validate the type. 
At first, it gives this false impression that it would validate it, but it doesn't.

Even with using `enforce: true`, it just checks for the key to be present. Not the type.

**Comment by ejpcmac** [comment] 2022-10-11 11:47
`typed_struct` helps you define a `@type` for a given struct by writing less code, it does not check anything. You then need to use Dialyzer or other type-checking tools to type-check your code. This is how Elixir currently works.

[Domo](https://github.com/IvanRublev/Domo) is known to work with TypedStruct, though I’ve not used it myself yet.

I’m closing this one as it is essentially a duplicate of #3.

**Closed as completed by ejpcmac** 2022-10-11 11:47 UTC
Labels: R:Duplicate
